FROM node:12.13.0-alpine

ENV CONTAINER_PATH /usr/src/app

RUN mkdir -p $CONTAINER_PATH

COPY . $CONTAINER_PATH
WORKDIR $CONTAINER_PATH

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "start"]
#ENTRYPOINT ["/bin/sh", "-c", "while true; do sleep 1; done"]
